apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysdigcloud-collector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: collector
    spec:
      containers:
        - name: collector
          image: quay.io/sysdig/sysdigcloud-backend:494
          volumeMounts:
            - name: logs
              mountPath: /var/log/sysdigcloud
            - name: config
              mountPath: /opt/kubernets_config
            - name: ssl
              mountPath: /opt/certs/
          env:
            - name: ROLES
              value: collector
            - name: LOG_ROLE
              value: collector
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: api.url
            - name: JVM_EXTRA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: sysdigcloud.jvm.options
          readinessProbe:
            tcpSocket:
              port: 6000
            initialDelaySeconds: 30
            timeoutSeconds: 2
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
      volumes:
        - name: logs
        - name: config
          configMap:
            name: sysdigcloud-config
        - name: ssl
          secret:
            secretName: sysdigcloud-ssl-secret